"""initial identity spine and osint tables

Revision ID: 54460060a12f
Revises: 
Create Date: 2026-09-03 16:41:26.453193

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54460060a12f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fir_no', sa.String(length=64), nullable=True),
    sa.Column('police_station', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sherlocks'
    )
    op.create_table('llm_cache',
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('input_hash'),
    schema='sherlocks'
    )
    op.create_table('person',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('canonical_cnic', sa.String(length=13), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('merged_into', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merged_into'], ['sherlocks.person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sherlocks'
    )
    op.create_index(op.f('ix_sherlocks_person_canonical_cnic'), 'person', ['canonical_cnic'], unique=False, schema='sherlocks')
    op.create_index(op.f('ix_sherlocks_person_merged_into'), 'person', ['merged_into'], unique=False, schema='sherlocks')
    op.create_table('sherlocks_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_file_path', sa.String(length=500), nullable=True),
    sa.Column('result_excel_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sherlocks'
    )
    op.create_table('case_person',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['sherlocks.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['sherlocks.person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'person_id', name='uq_case_person'),
    schema='sherlocks'
    )
    op.create_table('identifier',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value_norm', sa.String(length=255), nullable=False),
    sa.Column('value_raw', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['sherlocks.person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value_norm', name='uq_identifier_kind_value'),
    schema='sherlocks'
    )
    op.create_index('ix_identifier_person', 'identifier', ['person_id'], unique=False, schema='sherlocks')
    op.create_table('osint_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tools_planned', sa.Integer(), nullable=False),
    sa.Column('tools_run', sa.Integer(), nullable=False),
    sa.Column('tools_succeeded', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['sherlocks.cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['sherlocks.person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sherlocks'
    )
    op.create_index(op.f('ix_sherlocks_osint_run_job_id'), 'osint_run', ['job_id'], unique=False, schema='sherlocks')
    op.create_table('osint_finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('verified_by_user', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['sherlocks.person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['sherlocks.osint_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sherlocks'
    )
    op.create_index('ix_osint_finding_run_tool', 'osint_finding', ['run_id', 'tool'], unique=False, schema='sherlocks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_osint_finding_run_tool', table_name='osint_finding', schema='sherlocks')
    op.drop_table('osint_finding', schema='sherlocks')
    op.drop_index(op.f('ix_sherlocks_osint_run_job_id'), table_name='osint_run', schema='sherlocks')
    op.drop_table('osint_run', schema='sherlocks')
    op.drop_index('ix_identifier_person', table_name='identifier', schema='sherlocks')
    op.drop_table('identifier', schema='sherlocks')
    op.drop_table('case_person', schema='sherlocks')
    op.drop_table('sherlocks_job', schema='sherlocks')
    op.drop_index(op.f('ix_sherlocks_person_merged_into'), table_name='person', schema='sherlocks')
    op.drop_index(op.f('ix_sherlocks_person_canonical_cnic'), table_name='person', schema='sherlocks')
    op.drop_table('person', schema='sherlocks')
    op.drop_table('llm_cache', schema='sherlocks')
    op.drop_table('cases', schema='sherlocks')
    # ### end Alembic commands ###
